### ISSUE TITLE
Non-issue

### ISSUE THREAD

**Issue by spiside** [mmcloughlin/globe#1]
Just wanna say, this is pretty lit 🔥📣🔥

**Comment by mandatoryprogrammer** [comment]
Oi, it's 🔥!

**Comment by tidwall** [comment]
Wow! This is really awesome!!

**Comment by mehrdadrad** [comment]
Great job!

**Comment by evaryont** [comment]
This is fantastic. I'm not sure how I'd immediately use it, but I can't wait to come up with an excuse to do so!

**Comment by mmcloughlin** [comment]
Thanks all! Really appreciate your comments!
